
version: '3.4'

services:
  gitinsight:
    image: gitinsight
    build:
      context: .
      dockerfile: GitInsight/Dockerfile
    volumes:
      - .:/allsrc
      - ~/.vsdbg:/remote_debugger:rw
    command: "/allsrc -m f"
