version: '3.4'

services:
  gitinsight:
    container_name: gitinsight_app
    image: gitinsight
    build:
      context: .
      dockerfile: GitInsight/Dockerfile
    networks:
      - gitinsight

  db:
    container_name: gitinsight_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: gitinsight
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "54320:5432"
    networks:
      - gitinsight

networks:
  gitinsight:
    name: gitinsight
    driver: bridge
