# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gitinsight
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
